version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

project_name: cloudtrail-log-parser

builds:
  - id: binary
    dir: .
    main: ./cmd/main.go
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=lambda.norpc
      - -trimpath
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -s -w
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: lambda
    dir: .
    main: ./cmd/main.go
    binary: "bootstrap"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=lambda.norpc
      - -trimpath
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -s -w
      - -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    ids: [binary]
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: lambda
    ids: [lambda]
    formats: ["zip"]
    name_template: "{{ .ProjectName }}-lambda_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

snapshot:
  version_template: "{{ .Tag }}-next"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  draft: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^build:"

  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Security"
      regexp: "^.*sec[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
